
--- # begins a new section
list:
  - red
  - green
  - blue
another-list: [red, green, blue]

# Hash (or objects or dictionary)
name: Mukendi Mputu
age: 29

compact-hash: { name: Mukendi Mputu, age: 29 }


Codeblock: | # introduces a textblock respecting linebreaks
  print something
  exit


textblock: > # introduces a textblock conserving spaces but ignoring linebreaks
  Ignoring this
  linebreak.

  But keeping the spaces
  in between.
